### ISSUE TITLE
missing argument to handle 1Fichier hosting

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [GilGalaad/duplicity-rclone#10]
Hi,

I've been using the latest duplicity version with rclone backend recently but I kept having troubles with 1Fichier API flagging my connection as flooding.

I solved it by adding arguments to rclone : `--transfers=1 --multi-thread-streams=1` to line declaring `self.rclone_cmd`.

I think it should be considered to either add those arguments all the time or to add  a new argument to duplicity to enable them.

Have a nice day and thanks a lot for this project!

**Comment by kwloafman** [comment]
@thiswillbeyourgithub Please report this at https://gitlab.com/duplicity/duplicity so we can take a look at it.  I'm thinking the answer will be to add something like `--rclone-options` like we have with`-ssh-options` and -`-rsync-options`.  Would be much more flexible.

**Comment by GilGalaad** [comment]
I agree that the best solution, in the long term, is the ability to pass custom parameters to rclone. Now that rclone is an official backend, it makes sense.

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot for the quick reply. I'll create a post over there.
