### ISSUE TITLE
please provide config for rclone.conf path

### ISSUE THREAD

**Issue by cwseys** [GilGalaad/duplicity-rclone#4]
Hello,
  Would it be easy to provide a way to pass the backend a non-default location for the rclone config file?
  This backend is making duplicity work soooo much better!
Thanks!
C.

**Comment by GilGalaad** [comment]
sorry for the late answer.
you can pass all rclone option as environment variable. the one to select a non standard config file should be RCLONE_CONFIG.
please refer to rclone docs :)
