### ISSUE TITLE
Integration into duplicity

### ISSUE THREAD

**Issue by kwloafman** [GilGalaad/duplicity-rclone#6]
Hi,

Kenneth Loafman here.  I'm the maintainer of duplicity backup.  I'm working on integrating your code into duplicity.  Since duplicity is GPL v2, and rclonebackend.py is v3, I'd like your permission to release it as v2 instead of v3.

...Thanks,
...Ken

**Comment by GilGalaad** [comment]
This is a **great** news!
I modified the license, and you can do whatever you want with this code,
I'm proud to be, in some form, part of your great software.
